### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by lkblkb** [DoggieLicc/doggie-bot#1]
Loved the mini mod so now I'm trying to use doggie-bot as a replacement. 

I have it installed on an ubuntu VM. 

However when I run the bot this happens. Any advice? :)
```

ubuntu@user:~/doggie-bot$ python3 main.py 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 672, in _load_from_module_spec
    setup(self)
  File "/home/ubuntu/doggie-bot/cogs/game.py", line 242, in setup
    bot.add_cog(GameCog(bot))
  File "/home/ubuntu/doggie-bot/cogs/game.py", line 101, in __init__
    client_id=bot.config['osu_client_id'],
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 51, in <module>
    asyncio.run(startup())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "main.py", line 44, in startup
    bot.load_extension(cog)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 732, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 677, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.game' raised an error: TypeError: string indices must be integers
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa4e59dc6d0>

```

**Comment by lkblkb** [comment]
I am guessing it's related to not having osu and maybe unslpash. I deployed my own instance of mini mod instead :D

**Comment by DoggieLicc** [comment]
> I am guessing it's related to not having osu and maybe unslpash. I deployed my own instance of mini mod instead :D

That is probably the problem, when I get back to my computer i'll try to add checks for osu/unsplash commands to see if there's a key present, and fix this type error. 

Thank you for liking my bots ;3

**Comment by DoggieLicc** [comment]
Altho Quick question, can you show your config file? (replace token with something else)

**Comment by lkblkb** [comment]
I entered 0 for osu client to see if it would ignore it and I did end up with a different error (didn't copy it down though)
```
ubuntu@user:~$ cat doggie-bot/config.yaml
bot_token:Oxxxxxxxxxxxxxxxxxxx.Yyyyyyyyyyyyyyyyyyyyyy
osu_client_id:0
osu_client_secret: secret-here```

**Comment by DoggieLicc** [comment]
Try to to the latest version of this bot and just put nothing for osu/unsplash keys

```yaml
bot_token: aaaaaatoken
osu_client_id: 
osu_client_secret: 
unsplash_api_key: 
```

**Comment by lkblkb** [comment]
Ok cool it works :raised_hands: 

It's picky about the space after the colon :sweat_smile:  took me a minute to figure that out
